title: [Jacob P. Mohrbutter]
description: "Security Blog"
author:
  name: "Jacob Mohrbutter"
  email: "jmohrbutter@gmail.com"
  url: "qu3b411.github.io"

baseurl: qu3b411.github.io/

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Qu3b411"
year : "2019"
